/* Generated By:JJTree: Do not edit this line. ASTargs.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTargs extends SimpleNode {
  public ASTargs(int id) {
    super(id);
  }

  public ASTargs(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8529b6d3259783a983cb91c1bb292c6 (do not edit this line) */
