/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTAssignment extends SimpleNode {
  private String name;
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(VizParser p, int id) {
    super(p, id);
  }
  
  public String getCode()
  {
  	String code = jjtGetChild(0).getCode() + " = ";
  	code += jjtGetChild(1).getCode() + ";";
  	
  	return code;
  }

  public void setName(String name)
  {
  	this.name = name;
  }
  
  public String getName()
  {
  	return this.name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a10835975e6d92f5a96851d2f6dc929b (do not edit this line) */
