/* Generated By:JJTree: Do not edit this line. ASTArgs.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTArgs extends SimpleNode {
  public ASTArgs(int id) {
    super(id);
  }

  public ASTArgs(VizParser p, int id) {
    super(p, id);
  }

  public String getCode()
  {
  	String code = "";
  	for (int i = 0; i < jjtGetNumChildren(); i++)
  	{
  		code += jjtGetChild(i).getCode() + (i < jjtGetNumChildren() -1 ? ", " : "");
  	}
  	return code;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4ac16c6c456c70fe824e7a9393d05dbe (do not edit this line) */
