/* Generated By:JJTree: Do not edit this line. ASTArrayDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTArrayDeclaration extends SimpleNode {
  public ASTArrayDeclaration(int id) {
    super(id);
  }

  public ASTArrayDeclaration(VizParser p, int id) {
    super(p, id);
  }

  public String getCode()
  {
  	String code = "{";
  	int numMembers = jjtGetNumChildren();
  	
  	for (int i = 0; i < numMembers; i++)
  	{
  		code += jjtGetChild(i).getCode() + (i < numMembers -1 ? ", " : "");
  	}
  	code += "}";
  	return code;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a99e17c2c5b1c951932a6ffcdf9eaab (do not edit this line) */
