/* Generated By:JJTree: Do not edit this line. ASTassignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTassignment extends SimpleNode {
  public ASTassignment(int id) {
    super(id);
  }

  public ASTassignment(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c70ad8915330830dc5de523ea162679 (do not edit this line) */
