/* Generated By:JJTree: Do not edit this line. ASTargs.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTargs extends SimpleNode {
  public ASTargs(int id) {
    super(id);
  }

  public ASTargs(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5dd8d5ccadc50f1aa43d458c31e7f40e (do not edit this line) */
