/* Generated By:JJTree: Do not edit this line. ASTASTFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTASTFunction extends SimpleNode {
  public ASTASTFunction(int id) {
    super(id);
  }

  public ASTASTFunction(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed72b85318325cc8e82e6fec4088d114 (do not edit this line) */
