/* Generated By:JJTree: Do not edit this line. ASTassignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTassignment extends SimpleNode {
  public ASTassignment(int id) {
    super(id);
  }

  public ASTassignment(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70b4d241e8cb80472e2fd4290e689af5 (do not edit this line) */
