/* Generated By:JJTree: Do not edit this line. ASTcall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTcall extends SimpleNode {
  public ASTcall(int id) {
    super(id);
  }

  public ASTcall(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3aa7913e8b1b08f2c10e2ad072af38b (do not edit this line) */
