/* Generated By:JJTree: Do not edit this line. ASTcall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTcall extends SimpleNode {
  public ASTcall(int id) {
    super(id);
  }

  public ASTcall(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6e6c55c41cccfc8b56004d6c3899159 (do not edit this line) */
