/* Generated By:JJTree: Do not edit this line. ASTcall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTcall extends SimpleNode {
  public ASTcall(int id) {
    super(id);
  }

  public ASTcall(VizParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3609af88e5ad930546e20843757b1dd (do not edit this line) */
