/* Generated By:JJTree: Do not edit this line. ASTfunDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTfunDecl extends SimpleNode {
  public ASTfunDecl(int id) {
    super(id);
  }

  public ASTfunDecl(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cfb4f7dceb5ffbbee7f6978899abdb3c (do not edit this line) */
