/* Generated By:JJTree: Do not edit this line. ASTId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(VizParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cecc25cd3253f712a93e9d224104b0f2 (do not edit this line) */
