/* Generated By:JJTree: Do not edit this line. ASTop.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTop extends SimpleNode {
  public ASTop(int id) {
    super(id);
  }

  public ASTop(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4f79573c46efe16effb3c4a0ad7f89c (do not edit this line) */
