/* Generated By:JJTree: Do not edit this line. ASTop.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTop extends SimpleNode {
  public ASTop(int id) {
    super(id);
  }

  public ASTop(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=98cf69da2470d92e17a1ea085c52fa65 (do not edit this line) */
