/* Generated By:JJTree: Do not edit this line. ASTparams.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTparams extends SimpleNode {
  public ASTparams(int id) {
    super(id);
  }

  public ASTparams(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=803e03d6f6dd6db0abcb90c61b9fb551 (do not edit this line) */
