/* Generated By:JJTree: Do not edit this line. ASTparams.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTparams extends SimpleNode {
  public ASTparams(int id) {
    super(id);
  }

  public ASTparams(VizParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3698feb48f0ac13ddda18d90d6efc096 (do not edit this line) */
