/* Generated By:JJTree: Do not edit this line. ASTprogram.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTprogram extends SimpleNode {
  public ASTprogram(int id) {
    super(id);
  }

  public ASTprogram(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b313d418656848d3fc7116cd3d28895f (do not edit this line) */
