/* Generated By:JJTree: Do not edit this line. ASTparams.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTparams extends SimpleNode {
  public ASTparams(int id) {
    super(id);
  }

  public ASTparams(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=016d11406b6228d17e19923eba247b67 (do not edit this line) */
