/* Generated By:JJTree: Do not edit this line. ASTprogram.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTprogram extends SimpleNode {
  public ASTprogram(int id) {
    super(id);
  }

  public ASTprogram(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90a1e1f4a8cb29d9c67035d71dbe98ad (do not edit this line) */
