/* Generated By:JJTree: Do not edit this line. ASTvar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTvar extends SimpleNode {
  public ASTvar(int id) {
    super(id);
  }

  public ASTvar(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=93e64ce65c84046ff60d8bde88be47b6 (do not edit this line) */
