/* Generated By:JJTree: Do not edit this line. ASTvarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTvarDecl extends SimpleNode {
  public ASTvarDecl(int id) {
    super(id);
  }

  public ASTvarDecl(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b345cbb784af6639c81ccff9956b9b0 (do not edit this line) */
