/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTVar extends SimpleNode {
  
  private String name;
  private boolean isArray = false;
  
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(VizParser p, int id) {
    super(p, id);
  }
  
  public void setName(String name)
  {
  	this.name = name;
  }
  
  public void setIsArray(boolean isArray)
  {
  	this.isArray = isArray;
  }
  public String getName(String name)
  {
  	return this.name;
  }

  public String getCode()
  {
  	return this.name  + (isArray ? "[" + jjtGetChild(0).getCode() + "]" : "");
  }
  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3bc443c3f9289b3c9914321f2c2471bc (do not edit this line) */
