/* Generated By:JJTree: Do not edit this line. ASTvar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package Interpreter;

public class ASTvar extends SimpleNode {
  public ASTvar(int id) {
    super(id);
  }

  public ASTvar(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e46d51c01cc6289d326bb5570fcea146 (do not edit this line) */
