/* Generated By:JJTree: Do not edit this line. ASTvarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTvarDecl extends SimpleNode {
  public ASTvarDecl(int id) {
    super(id);
  }

  public ASTvarDecl(VizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b677d9d66b8fa4850f155eb31176d1f (do not edit this line) */
