/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(VizParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VizParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4fd06b0ecd973ae9f5151fe3a3be5c78 (do not edit this line) */
