/* Generated By:JavaCC: Do not edit this line. VizParserConstants.java */
package Interpreter;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VizParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 1;
  /** RegularExpression Id. */
  int VAR = 2;
  /** RegularExpression Id. */
  int NUM = 3;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int LTBCE = 6;
  /** RegularExpression Id. */
  int RTBCE = 7;
  /** RegularExpression Id. */
  int LTBCR = 8;
  /** RegularExpression Id. */
  int RTBCR = 9;
  /** RegularExpression Id. */
  int LTPRN = 10;
  /** RegularExpression Id. */
  int RTPRN = 11;
  /** RegularExpression Id. */
  int SEMI = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int EQL = 16;
  /** RegularExpression Id. */
  int OP = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"def\"",
    "\"var\"",
    "<NUM>",
    "<ID>",
    "<LETTER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "<OP>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
