/* Generated By:JavaCC: Do not edit this line. VizParserTreeConstants.java Version 4.1d1 */
public interface VizParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTID = 3;
  public int JJTFUNCTION = 4;
  public int JJTCALL = 5;
  public int JJTVAR = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTARGS = 8;
  public int JJTPARAMS = 9;
  public int JJTOP = 10;


  public String[] jjtNodeName = {
    "program",
    "void",
    "VarDecl",
    "Id",
    "Function",
    "Call",
    "Var",
    "assignment",
    "args",
    "params",
    "op",
  };
}
/* JavaCC - OriginalChecksum=88e0fe6a67db829db2d9acd507bd8400 (do not edit this line) */
