/* Generated By:JavaCC: Do not edit this line. VizParserTreeConstants.java Version 4.1d1 */
public interface VizParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATIONLIST = 1;
  public int JJTDECLARATION = 2;
  public int JJTVARDECL = 3;
  public int JJTID = 4;
  public int JJTVOID = 5;
  public int JJTFUNCTION = 6;
  public int JJTCALL = 7;
  public int JJTVAR = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTEXPRESSION = 10;
  public int JJTARGS = 11;
  public int JJTPARAMS = 12;
  public int JJTOP = 13;


  public String[] jjtNodeName = {
    "Program",
    "DeclarationList",
    "Declaration",
    "VarDecl",
    "Id",
    "void",
    "Function",
    "Call",
    "Var",
    "assignment",
    "Expression",
    "args",
    "params",
    "op",
  };
}
/* JavaCC - OriginalChecksum=dfae5bec22d29c81109cf9247ed24013 (do not edit this line) */
