/* Generated By:JavaCC: Do not edit this line. VizParserVisitor.java Version 4.1d1 */
public interface VizParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTCall node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTassignment node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTargs node, Object data);
  public Object visit(ASTparams node, Object data);
  public Object visit(ASTop node, Object data);
}
/* JavaCC - OriginalChecksum=8fb2ee70bc04043124efd082615ded34 (do not edit this line) */
