/* Generated By:JavaCC: Do not edit this line. VizParserVisitor.java Version 4.1d1 */
package Interpreter;

public interface VizParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDeclarationList node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTCall node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTassignment node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTargs node, Object data);
  public Object visit(ASTparams node, Object data);
  public Object visit(ASTop node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=34176909ce6991b0bdb49f9ab7f4f10c (do not edit this line) */
