/* Generated By:JavaCC: Do not edit this line. VizParserVisitor.java Version 4.1d1 */
package Interpreter;

public interface VizParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDeclarationList node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTArrayDeclaration node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTStatementList node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTCall node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTArgs node, Object data);
  public Object visit(ASTOp node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=c4444c3e49fbd9fd64a3e27ad1567241 (do not edit this line) */
